"""Add Donation model

Revision ID: 143247abf442
Revises: 2e7dda85b68a
Create Date: 2023-10-06 14:03:41.022858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143247abf442'
down_revision = '2e7dda85b68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=False),
    sa.Column('fully_invested', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('full_amount > 0', name='full_amount_positive'),
    sa.CheckConstraint('full_amount >= invested_amount', name='full_amount_gt_invested_amount'),
    sa.CheckConstraint('invested_amount >= 0', name='invested_amount_not_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_donation_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
